name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'    # раз в сутки
  workflow_dispatch:

# Важно: даём права на запись, чтобы action мог пушить файлы
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: 'nikitaHAllo'        # оставь свой ник
          repo_token: ${{ secrets.GITHUB_TOKEN }} # обязательно

      - name: Push generated images to branch "output"
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
